### ISSUE TITLE
ThemeSelectorService not generated if no pages are generated

### ISSUE THREAD

**Issue by ralarcon** [microsoft/TemplateStudio#199]
Templates build is failling after PR #160. The integration tests have detected an issue with the latest changes while generating an empty project (no matter the Framework selected).

The ThemeSelectorService is not being generated if no pages are generated, which is the condition the test is forcing (no repro possible using the VsEmulator by now, but it is expected to be able to generate projects without pages in a near future).

Sample build error (From the GenerateEmptyProject test):
*Solution SplitView was not built successfully. \r\nErrors found: ViewModels\ShellNavigationItem.cs(52,17): error CS0234: The type or namespace name 'ThemeSelectorService' does not exist in the namespace 'SplitViewMVVMBasic.Services' (are you missing an assembly reference?) [F:\UIT\18_0706\Proj\SplitViewMVVMBasic\SplitViewMVVMBasic\SplitViewMVVMBasic.csproj]\r\nViewModels\ShellNavigationItem.cs(68,13): error CS0234: The type or namespace name 'ThemeSelectorService' does not exist in the namespace 'SplitViewM...*

@mrlacey if you can have a look on this and easly find what is needed to repair it great! If not, we can have a look on this tomorrow morning (GTM+1). You can repro the error by executing the test within the Tests.sln solution.
